### ISSUE TITLE
Is this project broken/incomplete?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/initrd_progs#1]
I've been making changes. See here: https://github.com/wdlkmpx/initrd_progs

If there is enough interest, perhaps it could be merged in the future..

**Comment by 01micko** [comment]
yeah sure. it needs updating; in particular things like busybox and ntfs-3g need maintaining.

Not a soul showed any interest whatsoever :sob: .. not much with petbuilds either.

Issue a pull request! I'll just merge it then test :tongue:

**Comment by wdlkmpx** [comment]
It's compiling all the apps in slacko and tahrpup.. and precise puppy with the latest Aboriginal Linux cross compiler (it switched to musl). I solved all the issues I found, so basically running build_all.sh will compile all the apps and will produce an initrd.gz file ready to be tested in your machine.

Now somebody has to compile those apps in an ARM machine I guess?
