### ISSUE TITLE
Is busybox.net dead?

### ISSUE THREAD

**Issue by ghost** [puppylinux-woof-CE/initrd_progs#10]
I tried to run build.sh here and it fails to download busybox-1.25.0.tar.bz2
http://busybox.net/downloads/ (Problem loading page)

Using this mirror (in /pkg/busybox_static/busybox_static.petbuild) works ok though:
URL=https://mirror.cgicoders.com/busybox.net

**Comment by wdlkmpx** [comment]
it's still down. i wonder what happened..

**Comment by ghost** [comment]
Working again! So I mark as solved.  :+1:
